### ISSUE TITLE
Could not identify ICCID 89312530002070XXXXXX

### ISSUE THREAD

**Issue by coderbyheart** [cellprobe/e118-iin-list#5]
Vendor: Sprint
IIN: `89 31 253`

**Comment by coderbyheart** [comment]
> It's the SIM card that came with my Samsung Galaxy S10+ (Android) when I bought it as an upgrade, staying with Sprint, about a year ago.

I wouldn't expect that these SIM cards work, after all they are not LTE-m SIMs.

**Comment by coderbyheart** [comment]
> Our iBasis SIM cards that come with e.g. 9160DKs have similar ICCID numbers, e.g. 893108931810XXXXXX, are we talking about the same type of number?

Yes, iBasis is using KPN SIMs

**Comment by lincolnthomas** [comment]
Ok, I wasn't sure which kinds of SIM cards you were looking to test. I won't use this, you can close the issue.

**Comment by coderbyheart** [comment]
Alright, I should mention that in the README.
